apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatex-be
  namespace: argosai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatex-be
  template:
    metadata:
      labels:
        app: gatex-be
    spec:
      containers:
      - name: gatex-be
        image: argo-gatex/gatex-be:1.0.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
