apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatex-be-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR-ORG/argo-manifest
    targetRevision: HEAD
    path: overlays/dev/gatex-be-service
  destination:
    server: https://kubernetes.default.svc
    namespace: gtx-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
