apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base/argo-gatex

replicas:
  - name: gatex-ui
    count: 1
  - name: gatex-be
    count: 1

images:
  - name: argo-gatex/gatex-ui
    newTag: v0.1.0-dev
  - name: argo-gatex/gatex-be
    newTag: v0.1.0-dev

commonLabels:
  environment: dev

patches:
  - target:
      kind: Deployment
      name: gatex-ui
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "128Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "256Mi"
  - target:
      kind: Deployment
      name: gatex-be
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "256Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"
