apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-gatex-be-service-config
  namespace: argocd-gatex-dev
data:
  APP_DB_HOST: 165.22.209.220
  APP_DB_PORT: '3306'
  APP_DB_USERNAME: sai
  APP_DB_DATABASE: xpparel-dev-gatex
