apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd-gatex-dev

resources:
  - ../../../base/gatex-be-service
  - config.yaml
  - secrets.yaml

# Image tag management for ArgoCD
images:
  - name: ghcr.io/sainani7799/argo-gatex/gatex-be
    newTag: 1.5.0-dev

# Patches for environment configuration
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: argocd-gate-be-deployment
    spec:
      template:
        spec:
          containers:
            - name: argo-gatex-be
              envFrom:
                - configMapRef:
                    name: argo-gatex-be-service-config
                - secretRef:
                    name: argo-gatex-be-service-env

commonLabels:
  app: argocd-gate-be-service
  environment: dev
  managed-by: argocd
