apiVersion: v1
kind: Secret
metadata:
  name: argo-gatex-be-service-env
  namespace: argocd-gatex-dev
type: Opaque
stringData:
  # These should be managed by your secret management solution (sealed-secrets, vault, etc)
  DATABASE_PASSWORD: sai
