apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd-gatex-dev

resources:
  - gatex-ui/deployment.yaml
  - gatex-ui/service.yaml

commonLabels:
  app: argo-gatex-ui-service
  managed-by: argocd

images:
  - name: ghcr.io/sainani7799/argo-gatex/gatex-ui
    newTag: 1.10.0-dev
