apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gtx-dev

resources:
  - ../../../base/gatex-ui-service
  - config.yaml
  - secrets.yaml

# Image tag management for ArgoCD
images:
  - name: ghcr.io/schemax-pte-ltd/gatex/gatex-ui
    newTag: 1.9.0-dev

# Patches for environment configuration
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: gatex-ui-deployment
    spec:
      template:
        spec:
          containers:
            - name: gatex-ui
              envFrom:
                - configMapRef:
                    name: gatex-ui-service-config
                - secretRef:
                    name: gatex-ui-service-env
              env:
                - name: K8S_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: K8S_POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: K8S_NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName

commonLabels:
  app: gatex-ui-service
  environment: dev
  managed-by: argocd
