apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd-gatex-dev

resources:
  - ../../../base/gatex-ui-service
  - config.yaml

# Patches for environment configuration
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: gatex-ui-deployment
      namespace: argocd-gatex-dev
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: argo-ghcr-secret
          containers:
            - name: gatex-ui
              envFrom:
                - configMapRef:
                    name: gatex-ui-service-config

commonLabels:
  app: argo-gatex-ui-service
  environment: dev
  managed-by: argocd
