apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-gate-be-deployment
  namespace: argocd-gatex-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-gate-be
  template:
    metadata:
      labels:
        app: argocd-gate-be
    spec:
      containers:
      - name: argo-gatex-be
        image: ghcr.io/sainani7799/argo-gatex/gatex-be:1.6.0-dev
        ports:
        - containerPort: 3338
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "400m"
