apiVersion: v1
kind: Service
metadata:
  name: argo-gatex-be-service
  namespace: argocd-gatex-dev
spec:
  selector:
    app: argocd-gate-be
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30081
