apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatex-ui-deployment
  namespace: gtx-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatex-ui
  template:
    metadata:
      labels:
        app: gatex-ui
    spec:
      containers:
      - name: gatex-ui
        image: ghcr.io/schemax-pte-ltd/gatex/gatex-ui:1.9.0-dev
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
