apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatex-ui-deployment
  namespace: argocd-gatex-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-gatex-ui
  template:
    metadata:
      labels:
        app: argo-gatex-ui
    spec:
      containers:
      - name: gatex-ui
        image: ghcr.io/sainani7799/argo-gatex/gatex-ui:1.6.0-dev
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
