apiVersion: v1
kind: Service
metadata:
  name: gatex-ui-service
  namespace: argocd-gatex-dev
spec:
  selector:
    app: argo-gatex-ui
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
