apiVersion: v1
kind: Service
metadata:
  name: gatex-ui-service
  namespace: gtx-dev
spec:
  selector:
    app: gatex-ui
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30080
